name: zimaos-e2e-legacy-unmanaged-cartesian-environment-cartesian-delete-add-composite-helper-to-main
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:4f90b33ddca9c4d4f06527070d6e503b16d71016edea036842be2a84e60c91cb
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-environment-cartesian-delete-add-composite-helper-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920121320-814225-update-legacy-unmanaged-cartesian-environment-cartesian-delete-add-composite-helper-to-main
      E2E_CART_0575_MAIN_LOCAL: baseline-local
      E2E_CART_0575_MAIN_UPSTREAM: upstream
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18775'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3@sha256:c899811bc4a1f63a1273c612e15f1bea6514a19c7b08143dbbdef3e8f882c38d
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-environment-cartesian-delete-add-composite-helper-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920121320-814225-update-legacy-unmanaged-cartesian-environment-cartesian-delete-add-composite-helper-to-main-helper
      E2E_CART_0575_HELPER_LOCAL: baseline-local
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-cartesian-environment-cartesian-delete-add-composite-helper-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-cartesian-environment-cartesian-delete-add-composite-helper-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged-cartesian environment cartesian-delete-add composite helper-to-main
    zh_CN: E2E legacy-unmanaged-cartesian environment cartesian-delete-add composite helper-to-main
  port_map: '18775'
  version: 1.1.0
  scheme: http
  index: /
