name: syncthing
services:
  syncthing:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
      ZIMAOS_E2E_UPGRADE_MARKER: zimaos-e2e-20260915072700-syncthing
    image: linuxserver/syncthing:2.1.5@sha256:fc46d69a06c282fac1934fe78d91985ca46d6a458f59da245e6b1d03d460ec12
    deploy:
      resources:
        reservations:
          memory: "256M"
    network_mode: bridge
    ports:
      - target: 8384
        published: "8384"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: udp
      - target: 21027
        published: "21027"
        protocol: udp
      - target: 8384
        published: "18384"
        protocol: tcp
    command: []
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA
        target: /DATA
      - type: bind
        source: /DATA/AppData/$AppID/e2e-upgrade
        target: /zimaos-e2e-upgrade/syncthing
    container_name: syncthing
x-casaos:
  id: org.icewhale.syncthing
  main: syncthing
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.icewhale.syncthing/assets/icon.svg
  title:
    en_US: Syncthing
  index: /
  port_map: "8384"
  version: "2.1.5"
