name: zimaos-e2e-command-local-delete-upstream-modify-single
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-command-local-delete-upstream-modify-single-web
    environment:
      ZIMAOS_E2E_BASELINE: 20260917110228-81839-update-command-local-delete-upstream-modify-single
    restart: unless-stopped
    ports:
      - target: 80
        published: '18259'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
      - --name=baseline
x-casaos:
  id: org.zimaos.e2e.command-local-delete-upstream-modify-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.command-local-delete-upstream-modify-single/assets/icon.svg
  title:
    en_US: E2E Command Local-Delete-Upstream-Modify Single
    zh_CN: E2E Command Local-Delete-Upstream-Modify Single
  port_map: '18259'
  version: 1.0.0
