name: zimaos-e2e-legacy-previous-base-versioned-cache-miss-environment-cartesian-modify-modify-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.11.0
    container_name: zimaos-e2e-legacy-previous-base-versioned-cache-miss-environment-cartesian-modify-modify-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920121320-814225-update-legacy-previous-base-versioned-cache-miss-environment-cartesian-modify-modify-single-main-to-main
      E2E_CART_1626_MAIN_LOCAL: baseline-local
      E2E_CART_1626_MAIN_UPSTREAM: upstream
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19826'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-previous-base-versioned-cache-miss-environment-cartesian-modify-modify-single-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-previous-base-versioned-cache-miss-environment-cartesian-modify-modify-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-previous-base-versioned-cache-miss environment cartesian-modify-modify single main-to-main
    zh_CN: E2E legacy-previous-base-versioned-cache-miss environment cartesian-modify-modify single main-to-main
  port_map: '19826'
  version: 1.1.0
  scheme: http
  index: /
