name: rag-qa
services:
  rag-qa:
    image: fromxiaobai/rchat-back:v7
    container_name: rag-qa
    volumes:
      # Mount the data directory to persist the database and knowledge base files
      - /DATA/AppData/RAG-QA/backend/data:/app/data
      # Mount the config file to allow for external configuration
      # - ./backend/models_config.json:/app/models_config.json
    ports:
      - "8000:8000"
    networks:
      - rag
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 512M
  frontend:
    image: fromxiaobai/rchat-front:v7
    container_name: rchat-frontend
    ports:
      - "18300:3000"
    environment:
      # This tells the Next.js app inside the container where to find the backend API.
      # 'backend' is the service name defined above.
      - NEXT_PUBLIC_API_URL=http://rag-qa:8000
    depends_on:
      - rag-qa
    networks:
      - rag
    restart: unless-stopped
networks:
  rag:
    driver: bridge
x-casaos:
  architectures:
    - amd64
  author: CasaOS Team
  category: Chat
  description:
    en_US: RAG
  developer: IceWhale
  icon: ""
  main: rag-qa
  port_map: "18300"
  scheme: http
  screenshot_link:
    - ""
  tagline:
    en_US: RAG-QA
  title:
    en_US: RAG-QA