name: adminer
services:
  adminer:
    image: adminer:6.0.1@sha256:27a72b5b70f061e034132db92fffe6dcb556b49c9147cb3b1eb3f9d88f5dddbd
    deploy:
      resources:
        reservations:
          memory: 32M
    restart: always
    ports:
      - 8080:8080
      - target: 18080
        published: '18080'
        protocol: tcp
    container_name: adminer
    environment:
      E2E_UPSTREAM_ONLY: upstream-value
    volumes:
      - type: bind
        source: /DATA/AppData/org-icewhale-adminer/e2e-upstream
        target: /e2e-upstream
    command:
      - php
      - -S
      - '[::]:8080'
      - -t
      - /var/www/html
x-casaos:
  id: org.icewhale.adminer
  main: adminer
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.icewhale.adminer/assets/icon.svg
  title:
    en_US: Adminer
  port_map: '8080'
  version: 6.0.1
