name: zimaos-e2e-native-composite-cross-environment-modify-same-composite-helper-to-main
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-native-composite-cross-environment-modify-same-composite-helper-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923192050-1779572-update-native-composite-cross-environment-modify-same-composite-helper-to-main
      E2E_CASE_368_MAIN_A: baseline-a
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18568'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-native-composite-cross-environment-modify-same-composite-helper-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923192050-1779572-update-native-composite-cross-environment-modify-same-composite-helper-to-main-helper
      E2E_CASE_368_HELPER_A: baseline-a
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.native-composite-cross-environment-modify-same-composite-helper-to-main
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.native-composite-cross-environment-modify-same-composite-helper-to-main/assets/icon.svg
  title:
    en_US: E2E native-composite-cross environment modify-same composite helper-to-main
    zh_CN: E2E native-composite-cross environment modify-same composite helper-to-main
  port_map: '18568'
  version: 1.0.0
  scheme: http
  index: /
