name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-delete-unchanged-composite-main-to-main
services:
  web:
    image: traefik/whoami:v1.11.0
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-delete-unchanged-composite-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923205535-1808238-update-legacy-unmanaged-cartesian-restart-cartesian-delete-unchanged-composite-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19041'
        protocol: tcp
    command:
      - --port=80
    restart: unless-stopped
  helper:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-delete-unchanged-composite-main-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923205535-1808238-update-legacy-unmanaged-cartesian-restart-cartesian-delete-unchanged-composite-main-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    command:
      - --port=80
    restart: unless-stopped
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-cartesian-restart-cartesian-delete-unchanged-composite-main-to-main
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-cartesian-restart-cartesian-delete-unchanged-composite-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged-cartesian restart cartesian-delete-unchanged composite main-to-main
    zh_CN: E2E legacy-unmanaged-cartesian restart cartesian-delete-unchanged composite main-to-main
  port_map: '19041'
  version: 1.1.0
  scheme: http
  index: /
