name: zimaos-e2e-legacy-unmanaged-environment-delete-same-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    container_name: zimaos-e2e-legacy-unmanaged-environment-delete-same-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921171621-1205145-update-legacy-unmanaged-environment-delete-same-single-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18209'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-environment-delete-same-single-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-environment-delete-same-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged environment delete-same single main-to-main
    zh_CN: E2E legacy-unmanaged environment delete-same single main-to-main
  port_map: '18209'
  version: 1.1.0
  scheme: http
  index: /
