name: zimaos-e2e-volumes-add-different-composite
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:4f90b33ddca9c4d4f06527070d6e503b16d71016edea036842be2a84e60c91cb
    container_name: zimaos-e2e-volumes-add-different-composite-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260918050619-305930-update-volumes-add-different-composite
    restart: unless-stopped
    ports:
      - target: 80
        published: '18204'
        protocol: tcp
    command:
      - --port=80
    volumes:
      - type: bind
        source: /DATA/AppData/zimaos-e2e-volumes-add-different-composite/case-upstream-b
        target: /e2e-case-b
  helper:
    image: alpine:3.20@sha256:c64c687cbea9300178b30c95835354e34c4e4febc4badfe27102879de0483b5e
    container_name: zimaos-e2e-volumes-add-different-composite-helper
    network_mode: bridge
    restart: unless-stopped
    environment:
      E2E_SECONDARY_BASELINE: 20260918050619-305930-update-volumes-add-different-composite
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
x-casaos:
  id: org.zimaos.e2e.volumes-add-different-composite
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.volumes-add-different-composite/assets/icon.svg
  title:
    en_US: E2E Volumes Add-Different Composite
    zh_CN: E2E Volumes Add-Different Composite
  port_map: '18204'
  version: 1.1.0
