name: zimaos-e2e-legacy-unmanaged-cartesian-command-cartesian-modify-delete-composite-main-to-helper
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:4f90b33ddca9c4d4f06527070d6e503b16d71016edea036842be2a84e60c91cb
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-command-cartesian-modify-delete-composite-main-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260922123745-1463104-update-legacy-unmanaged-cartesian-command-cartesian-modify-delete-composite-main-to-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18958'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
      - --name=baseline-local-main-0758
      - --verbose=false
  helper:
    image: traefik/whoami:v1.10.3@sha256:c899811bc4a1f63a1273c612e15f1bea6514a19c7b08143dbbdef3e8f882c38d
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-command-cartesian-modify-delete-composite-main-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260922123745-1463104-update-legacy-unmanaged-cartesian-command-cartesian-modify-delete-composite-main-to-helper-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
      - --name=baseline-local-helper-0758
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-cartesian-command-cartesian-modify-delete-composite-main-to-helper
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-cartesian-command-cartesian-modify-delete-composite-main-to-helper/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged-cartesian command cartesian-modify-delete composite main-to-helper
    zh_CN: E2E legacy-unmanaged-cartesian command cartesian-modify-delete composite main-to-helper
  port_map: '18958'
  version: 1.1.0
  scheme: http
  index: /
