name: zimaos-e2e-legacy-previous-base-exact-history-command-cartesian-add-unchanged-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:f1c59fb1677f4711290c320d288e182adad7b84326d71cf5fb883893b07cd23d
    container_name: zimaos-e2e-legacy-previous-base-exact-history-command-cartesian-add-unchanged-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921215814-1252718-update-legacy-previous-base-exact-history-command-cartesian-add-unchanged-single-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19740'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-previous-base-exact-history-command-cartesian-add-unchanged-single-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-previous-base-exact-history-command-cartesian-add-unchanged-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-previous-base-exact-history command cartesian-add-unchanged single main-to-main
    zh_CN: E2E legacy-previous-base-exact-history command cartesian-add-unchanged single main-to-main
  port_map: '19740'
  version: 1.0.0
  scheme: http
  index: /
