name: zimaos-e2e-native-composite-cross-environment-add-same-composite-helper-to-helper
services:
  web:
    image: traefik/whoami:v1.11.0
    container_name: zimaos-e2e-native-composite-cross-environment-add-same-composite-helper-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920131236-829500-update-native-composite-cross-environment-add-same-composite-helper-to-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18563'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-native-composite-cross-environment-add-same-composite-helper-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920131236-829500-update-native-composite-cross-environment-add-same-composite-helper-to-helper-helper
      E2E_CASE_363_HELPER_A: upstream-a
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.native-composite-cross-environment-add-same-composite-helper-to-helper
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.native-composite-cross-environment-add-same-composite-helper-to-helper/assets/icon.svg
  title:
    en_US: E2E native-composite-cross environment add-same composite helper-to-helper
    zh_CN: E2E native-composite-cross environment add-same composite helper-to-helper
  port_map: '18563'
  version: 1.1.0
  scheme: http
  index: /
