name: zimaos-e2e-legacy-unmanaged-command-delete-same-composite-main-to-main
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:9564f83910c98c3bea640803d8014b5c586b4bd556906d1afab21c7e7f1e4d4c
    container_name: zimaos-e2e-legacy-unmanaged-command-delete-same-composite-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920061837-723448-update-legacy-unmanaged-command-delete-same-composite-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18210'
        protocol: tcp
    restart: unless-stopped
  helper:
    image: alpine:3.20@sha256:37753b2965043543542cd9d48cba044151052ca14fa72e6cbec4edf2a1490599
    container_name: zimaos-e2e-legacy-unmanaged-command-delete-same-composite-main-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920061837-723448-update-legacy-unmanaged-command-delete-same-composite-main-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
      - --name=baseline-helper
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-command-delete-same-composite-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-command-delete-same-composite-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged command delete-same composite main-to-main
    zh_CN: E2E legacy-unmanaged command delete-same composite main-to-main
  port_map: '18210'
  version: 1.1.0
  scheme: http
  index: /
