name: zimaos-e2e-legacy-previous-base-versionless-target-ports-cartesian-modify-unchanged-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-previous-base-versionless-target-ports-cartesian-modify-unchanged-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923003816-1570799-update-legacy-previous-base-versionless-target-ports-cartesian-modify-unchanged-single-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19780'
        protocol: tcp
      - target: 17320
        published: '47800'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-previous-base-versionless-target-ports-cartesian-modify-unchanged-single-main-to-main
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-previous-base-versionless-target-ports-cartesian-modify-unchanged-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-previous-base-versionless-target ports cartesian-modify-unchanged single main-to-main
    zh_CN: E2E legacy-previous-base-versionless-target ports cartesian-modify-unchanged single main-to-main
  port_map: '19780'
  version: 1.0.0
  scheme: http
  index: /
