name: zimaos-e2e-legacy-previous-base-versionless-target-volumes-cartesian-delete-add-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-previous-base-versionless-target-volumes-cartesian-delete-add-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921023814-992202-update-legacy-previous-base-versionless-target-volumes-cartesian-delete-add-single-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-previous-base-versionless-target-volumes-cartesian-delete-add-single-main-to-main/cart-baseline-local
        target: /e2e-cart-1593-local
    ports:
      - target: 80
        published: '19793'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-previous-base-versionless-target-volumes-cartesian-delete-add-single-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-previous-base-versionless-target-volumes-cartesian-delete-add-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-previous-base-versionless-target volumes cartesian-delete-add single main-to-main
    zh_CN: E2E legacy-previous-base-versionless-target volumes cartesian-delete-add single main-to-main
  port_map: '19793'
  version: 1.0.0
  scheme: http
  index: /
