name: zimaos-e2e-legacy-two-stage-cartesian-restart-cartesian-delete-modify-composite-main-to-helper
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:f1c59fb1677f4711290c320d288e182adad7b84326d71cf5fb883893b07cd23d
    container_name: zimaos-e2e-legacy-two-stage-cartesian-restart-cartesian-delete-modify-composite-main-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-two-stage-cartesian-restart-cartesian-delete-modify-composite-main-to-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19674'
        protocol: tcp
    command:
      - --port=80
    restart: unless-stopped
  helper:
    image: traefik/whoami:v1.10.3@sha256:f1c59fb1677f4711290c320d288e182adad7b84326d71cf5fb883893b07cd23d
    container_name: zimaos-e2e-legacy-two-stage-cartesian-restart-cartesian-delete-modify-composite-main-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-two-stage-cartesian-restart-cartesian-delete-modify-composite-main-to-helper-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    command:
      - --port=80
    restart: unless-stopped
x-casaos:
  id: org.zimaos.e2e.legacy-two-stage-cartesian-restart-cartesian-delete-modify-composite-main-to-helper
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-two-stage-cartesian-restart-cartesian-delete-modify-composite-main-to-helper/assets/icon.svg
  title:
    en_US: E2E legacy-two-stage-cartesian restart cartesian-delete-modify composite main-to-helper
    zh_CN: E2E legacy-two-stage-cartesian restart cartesian-delete-modify composite main-to-helper
  port_map: '19674'
  version: 1.0.0
  scheme: http
  index: /
