name: zimaos-e2e-legacy-two-stage-edit-ports-local-modify-upstream-unchanged-composite-helper-to-main
services:
  web:
    image: traefik/whoami:v1.11.0
    container_name: zimaos-e2e-legacy-two-stage-edit-ports-local-modify-upstream-unchanged-composite-helper-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920083536-764613-update-legacy-two-stage-edit-ports-local-modify-upstream-unchanged-composite-helper-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18206'
        protocol: tcp
      - target: 10024
        published: '30048'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-two-stage-edit-ports-local-modify-upstream-unchanged-composite-helper-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920083536-764613-update-legacy-two-stage-edit-ports-local-modify-upstream-unchanged-composite-helper-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
    ports:
      - target: 10026
        published: '30052'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.legacy-two-stage-edit-ports-local-modify-upstream-unchanged-composite-helper-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-two-stage-edit-ports-local-modify-upstream-unchanged-composite-helper-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-two-stage-edit ports local-modify-upstream-unchanged composite helper-to-main
    zh_CN: E2E legacy-two-stage-edit ports local-modify-upstream-unchanged composite helper-to-main
  port_map: '18206'
  version: 1.1.0
  scheme: http
  index: /
