name: zimaos-e2e-legacy-unmanaged-ports-local-delete-upstream-unchanged-composite-main-to-main
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    container_name: zimaos-e2e-legacy-unmanaged-ports-local-delete-upstream-unchanged-composite-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920033520-673872-update-legacy-unmanaged-ports-local-delete-upstream-unchanged-composite-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18224'
        protocol: tcp
      - target: 10096
        published: '30192'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: alpine:3.20@sha256:45e09956dc667c5eff3583c9d94830261fb1ca0be10a0a7db36266edf5de9e1d
    container_name: zimaos-e2e-legacy-unmanaged-ports-local-delete-upstream-unchanged-composite-main-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920033520-673872-update-legacy-unmanaged-ports-local-delete-upstream-unchanged-composite-main-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
    ports:
      - target: 10098
        published: '30196'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-ports-local-delete-upstream-unchanged-composite-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-ports-local-delete-upstream-unchanged-composite-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged ports local-delete-upstream-unchanged composite main-to-main
    zh_CN: E2E legacy-unmanaged ports local-delete-upstream-unchanged composite main-to-main
  port_map: '18224'
  version: 1.1.0
  scheme: http
  index: /
