name: zimaos-e2e-legacy-managed-cartesian-ports-cartesian-modify-unchanged-composite-helper-to-main
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-managed-cartesian-ports-cartesian-modify-unchanged-composite-helper-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-managed-cartesian-ports-cartesian-modify-unchanged-composite-helper-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19155'
        protocol: tcp
      - target: 12910
        published: '37730'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-managed-cartesian-ports-cartesian-modify-unchanged-composite-helper-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-managed-cartesian-ports-cartesian-modify-unchanged-composite-helper-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
    ports:
      - target: 12911
        published: '37733'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.legacy-managed-cartesian-ports-cartesian-modify-unchanged-composite-helper-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-managed-cartesian-ports-cartesian-modify-unchanged-composite-helper-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-managed-cartesian ports cartesian-modify-unchanged composite helper-to-main
    zh_CN: E2E legacy-managed-cartesian ports cartesian-modify-unchanged composite helper-to-main
  port_map: '19155'
  version: 1.0.0
  scheme: http
  index: /
