name: zimaos-e2e-restart-local-delete-upstream-unchanged-single
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    container_name: zimaos-e2e-restart-local-delete-upstream-unchanged-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260918063303-327707-update-restart-local-delete-upstream-unchanged-single
    ports:
      - target: 80
        published: '18215'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    restart: unless-stopped
x-casaos:
  id: org.zimaos.e2e.restart-local-delete-upstream-unchanged-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.restart-local-delete-upstream-unchanged-single/assets/icon.svg
  title:
    en_US: E2E Restart Local-Delete-Upstream-Unchanged Single
    zh_CN: E2E Restart Local-Delete-Upstream-Unchanged Single
  port_map: '18215'
  version: 1.1.0
