name: zimaos-e2e-restart-local-empty-upstream-value-single
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:f1c59fb1677f4711290c320d288e182adad7b84326d71cf5fb883893b07cd23d
    container_name: zimaos-e2e-restart-local-empty-upstream-value-single-web
    environment:
      ZIMAOS_E2E_BASELINE: 20260917103026-76552-update-restart-local-empty-upstream-value-single
    ports:
      - target: 80
        published: '18279'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    restart: unless-stopped
x-casaos:
  id: org.zimaos.e2e.restart-local-empty-upstream-value-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.restart-local-empty-upstream-value-single/assets/icon.svg
  title:
    en_US: E2E Restart Local-Empty-Upstream-Value Single
    zh_CN: E2E Restart Local-Empty-Upstream-Value Single
  port_map: '18279'
  version: 1.0.0
