name: zimaos-e2e-restart-local-empty-upstream-value-single
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:c899811bc4a1f63a1273c612e15f1bea6514a19c7b08143dbbdef3e8f882c38d
    container_name: zimaos-e2e-restart-local-empty-upstream-value-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917212707-222382-update-restart-local-empty-upstream-value-single
    ports:
      - target: 80
        published: '18215'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    restart: unless-stopped
x-casaos:
  id: org.zimaos.e2e.restart-local-empty-upstream-value-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.restart-local-empty-upstream-value-single/assets/icon.svg
  title:
    en_US: E2E Restart Local-Empty-Upstream-Value Single
    zh_CN: E2E Restart Local-Empty-Upstream-Value Single
  port_map: '18215'
  version: 1.0.0
