name: zimaos-e2e-environment-add-different-single
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-environment-add-different-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260918031822-278070-update-environment-add-different-single
    restart: unless-stopped
    ports:
      - target: 80
        published: '18203'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.environment-add-different-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.environment-add-different-single/assets/icon.svg
  title:
    en_US: E2E Environment Add-Different Single
    zh_CN: E2E Environment Add-Different Single
  port_map: '18203'
  version: 1.0.0
