name: vocechat
services:
  vocechat:
    environment:
      TZ: $TZ
      ZIMAOS_E2E_UPGRADE_MARKER: zimaos-e2e-20260915072700-vocechat
    image: privoce/vocechat-server:v0.5.36@sha256:bb324e9ce9ba5e53d863e381d7c272688a377aff39e7063438ab7fe5df7b29c5
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 3000
        published: "3009"
        protocol: tcp
      - target: 3000
        published: "13009"
        protocol: tcp
    command: []
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/home/vocechat-server/data
        target: /home/vocechat-server/data
      - type: bind
        source: /DATA/AppData/$AppID/e2e-upgrade
        target: /zimaos-e2e-upgrade/vocechat
    container_name: vocechat
x-casaos:
  id: org.icewhale.vocechat
  main: vocechat
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.icewhale.vocechat/assets/icon.svg
  title:
    en_US: VoceChat
  index: /
  port_map: "3009"
  version: "0.5.36"
