name: zimaos-e2e-native-composite-cross-ports-delete-same-composite-helper-to-helper
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:9564f83910c98c3bea640803d8014b5c586b4bd556906d1afab21c7e7f1e4d4c
    container_name: zimaos-e2e-native-composite-cross-ports-delete-same-composite-helper-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260922095009-1422902-update-native-composite-cross-ports-delete-same-composite-helper-to-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18611'
        protocol: tcp
      - target: 11644
        published: '33288'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3@sha256:f1c59fb1677f4711290c320d288e182adad7b84326d71cf5fb883893b07cd23d
    container_name: zimaos-e2e-native-composite-cross-ports-delete-same-composite-helper-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260922095009-1422902-update-native-composite-cross-ports-delete-same-composite-helper-to-helper-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.native-composite-cross-ports-delete-same-composite-helper-to-helper
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.native-composite-cross-ports-delete-same-composite-helper-to-helper/assets/icon.svg
  title:
    en_US: E2E native-composite-cross ports delete-same composite helper-to-helper
    zh_CN: E2E native-composite-cross ports delete-same composite helper-to-helper
  port_map: '18611'
  version: 1.1.0
  scheme: http
  index: /
