name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-add-unchanged-composite-helper-to-helper
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-add-unchanged-composite-helper-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923003816-1570799-update-legacy-unmanaged-cartesian-restart-cartesian-add-unchanged-composite-helper-to-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19012'
        protocol: tcp
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-add-unchanged-composite-helper-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923003816-1570799-update-legacy-unmanaged-cartesian-restart-cartesian-add-unchanged-composite-helper-to-helper-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-cartesian-restart-cartesian-add-unchanged-composite-helper-to-helper
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-cartesian-restart-cartesian-add-unchanged-composite-helper-to-helper/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged-cartesian restart cartesian-add-unchanged composite helper-to-helper
    zh_CN: E2E legacy-unmanaged-cartesian restart cartesian-add-unchanged composite helper-to-helper
  port_map: '19012'
  version: 1.0.0
  scheme: http
  index: /
