name: zimaos-e2e-volumes-local-delete-upstream-modify-single
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-volumes-local-delete-upstream-modify-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917144513-127766-update-volumes-local-delete-upstream-modify-single
    restart: unless-stopped
    ports:
      - target: 80
        published: '18211'
        protocol: tcp
    command:
      - --port=80
    volumes:
      - type: bind
        source: /DATA/AppData/zimaos-e2e-volumes-local-delete-upstream-modify-single/case-base-a
        target: /e2e-case-a
x-casaos:
  id: org.zimaos.e2e.volumes-local-delete-upstream-modify-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.volumes-local-delete-upstream-modify-single/assets/icon.svg
  title:
    en_US: E2E Volumes Local-Delete-Upstream-Modify Single
    zh_CN: E2E Volumes Local-Delete-Upstream-Modify Single
  port_map: '18211'
  version: 1.0.0
