name: zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-unchanged-composite-helper-to-main
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:4f90b33ddca9c4d4f06527070d6e503b16d71016edea036842be2a84e60c91cb
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-unchanged-composite-helper-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260922115813-1453972-update-legacy-unmanaged-cartesian-volumes-cartesian-modify-unchanged-composite-helper-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-unchanged-composite-helper-to-main/cart-baseline-local
        target: /e2e-cart-0699-local
    ports:
      - target: 80
        published: '18899'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3@sha256:c899811bc4a1f63a1273c612e15f1bea6514a19c7b08143dbbdef3e8f882c38d
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-unchanged-composite-helper-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260922115813-1453972-update-legacy-unmanaged-cartesian-volumes-cartesian-modify-unchanged-composite-helper-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-unchanged-composite-helper-to-main/cart-baseline-local-helper
        target: /e2e-cart-0699-local-helper
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-cartesian-volumes-cartesian-modify-unchanged-composite-helper-to-main
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-cartesian-volumes-cartesian-modify-unchanged-composite-helper-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged-cartesian volumes cartesian-modify-unchanged composite helper-to-main
    zh_CN: E2E legacy-unmanaged-cartesian volumes cartesian-modify-unchanged composite helper-to-main
  port_map: '18899'
  version: 1.1.0
  scheme: http
  index: /
