name: zimaos-e2e-image-single
services:
  web:
    image: traefik/whoami:latest@sha256:fb8458a97e9695115b0367e5ecf2a1a72de48b306acccccd01455b46334d2300
    container_name: zimaos-e2e-image-single-web
    restart: unless-stopped
    ports:
      - target: 80
        published: '18105'
        protocol: tcp
    environment:
      ZIMAOS_E2E_BASELINE: 20260921062455-1057246-image-single
      E2E_SHARED: baseline
      E2E_LOCAL_DELETE_UPSTREAM_MODIFY: baseline
      E2E_LOCAL_KEEP_UPSTREAM_DELETE: baseline
      E2E_LOCAL_EMPTY_UPSTREAM_VALUE: baseline
      E2E_LOCAL_VALUE_UPSTREAM_EMPTY: baseline
      E2E_BOTH_EMPTY: baseline
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.image-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.image-single/assets/icon.svg
  title:
    en_US: E2E Image Single
    zh_CN: E2E Image Single
  port_map: '18105'
  version: 1.0.0
  scheme: http
  index: /
