name: 2fauth
services:
  2fauth:
    image: 2fauth/2fauth:8.0.2@sha256:9737f4f8a00841d26822a6fc15bef7a11e17a6de7f5647b4e195c12b057bf643
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /2fauth
    environment:
      APP_KEY: SomeRandomStringOf32CharsExactly
    container_name: 2fauth
x-casaos:
  id: org.icewhale.2fauth
  main: 2fauth
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.icewhale.2fauth/assets/icon.svg
  title:
    en_US: 2FAuth
  index: /
  port_map: "8000"
  version: "8.0.2"
