name: zimaos-e2e-legacy-two-stage-cartesian-ports-cartesian-add-modify-composite-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:f1c59fb1677f4711290c320d288e182adad7b84326d71cf5fb883893b07cd23d
    container_name: zimaos-e2e-legacy-two-stage-cartesian-ports-cartesian-add-modify-composite-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921091825-1094803-update-legacy-two-stage-cartesian-ports-cartesian-add-modify-composite-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19449'
        protocol: tcp
      - target: 15997
        published: '44492'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3@sha256:f1c59fb1677f4711290c320d288e182adad7b84326d71cf5fb883893b07cd23d
    container_name: zimaos-e2e-legacy-two-stage-cartesian-ports-cartesian-add-modify-composite-main-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921091825-1094803-update-legacy-two-stage-cartesian-ports-cartesian-add-modify-composite-main-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
    ports:
      - target: 15999
        published: '44497'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.legacy-two-stage-cartesian-ports-cartesian-add-modify-composite-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-two-stage-cartesian-ports-cartesian-add-modify-composite-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-two-stage-cartesian ports cartesian-add-modify composite main-to-main
    zh_CN: E2E legacy-two-stage-cartesian ports cartesian-add-modify composite main-to-main
  port_map: '19449'
  version: 1.0.0
  scheme: http
  index: /
