name: zimaos-e2e-legacy-unmanaged-cartesian-environment-cartesian-modify-delete-composite-helper-to-helper
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-environment-cartesian-modify-delete-composite-helper-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920003507-630016-update-legacy-unmanaged-cartesian-environment-cartesian-modify-delete-composite-helper-to-helper
      E2E_CART_0004_MAIN: baseline
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18204'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-environment-cartesian-modify-delete-composite-helper-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920003507-630016-update-legacy-unmanaged-cartesian-environment-cartesian-modify-delete-composite-helper-to-helper-helper
      E2E_CART_0004_HELPER: baseline
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-cartesian-environment-cartesian-modify-delete-composite-helper-to-helper
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-cartesian-environment-cartesian-modify-delete-composite-helper-to-helper/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged-cartesian environment cartesian-modify-delete composite helper-to-helper
    zh_CN: E2E legacy-unmanaged-cartesian environment cartesian-modify-delete composite helper-to-helper
  port_map: '18204'
  version: 1.0.0
  scheme: http
  index: /
