name: zimaos-e2e-command-add-same-single
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-command-add-same-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260918055056-316649-update-command-add-same-single
    restart: unless-stopped
    ports:
      - target: 80
        published: '18201'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
x-casaos:
  id: org.zimaos.e2e.command-add-same-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.command-add-same-single/assets/icon.svg
  title:
    en_US: E2E Command Add-Same Single
    zh_CN: E2E Command Add-Same Single
  port_map: '18201'
  version: 1.0.0
