name: zimaos-e2e-command-add-same-single
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:4f90b33ddca9c4d4f06527070d6e503b16d71016edea036842be2a84e60c91cb
    container_name: zimaos-e2e-command-add-same-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917185928-187279-update-command-add-same-single
    restart: unless-stopped
    ports:
      - target: 80
        published: '18201'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
      - --name=same
x-casaos:
  id: org.zimaos.e2e.command-add-same-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.command-add-same-single/assets/icon.svg
  title:
    en_US: E2E Command Add-Same Single
    zh_CN: E2E Command Add-Same Single
  port_map: '18201'
  version: 1.1.0
