name: zimaos-e2e-legacy-managed-command-add-different-composite-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-managed-command-add-different-composite-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-managed-command-add-different-composite-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18396'
        protocol: tcp
    restart: unless-stopped
  helper:
    image: alpine:3.20
    container_name: zimaos-e2e-legacy-managed-command-add-different-composite-main-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-managed-command-add-different-composite-main-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
x-casaos:
  id: org.zimaos.e2e.legacy-managed-command-add-different-composite-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-managed-command-add-different-composite-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-managed command add-different composite main-to-main
    zh_CN: E2E legacy-managed command add-different composite main-to-main
  port_map: '18396'
  version: 1.0.0
  scheme: http
  index: /
