name: zimaos-e2e-ports-add-same-single
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:c899811bc4a1f63a1273c612e15f1bea6514a19c7b08143dbbdef3e8f882c38d
    container_name: zimaos-e2e-ports-add-same-single-web
    environment:
      ZIMAOS_E2E_BASELINE: 20260917110228-81839-update-ports-add-same-single
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    ports: []
x-casaos:
  id: org.zimaos.e2e.ports-add-same-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.ports-add-same-single/assets/icon.svg
  title:
    en_US: E2E Ports Add-Same Single
    zh_CN: E2E Ports Add-Same Single
  port_map: '18217'
  version: 1.0.0
