name: zimaos-e2e-ports-add-same-single
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    container_name: zimaos-e2e-ports-add-same-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917140034-116715-update-ports-add-same-single
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    ports:
      - target: 10002
        published: '30006'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.ports-add-same-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.ports-add-same-single/assets/icon.svg
  title:
    en_US: E2E Ports Add-Same Single
    zh_CN: E2E Ports Add-Same Single
  port_map: '18201'
  version: 1.1.0
