name: zimaos-e2e-legacy-managed-cartesian-ports-cartesian-modify-add-composite-helper-to-main
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    container_name: zimaos-e2e-legacy-managed-cartesian-ports-cartesian-modify-add-composite-helper-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923205535-1808238-update-legacy-managed-cartesian-ports-cartesian-modify-add-composite-helper-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19143'
        protocol: tcp
      - target: 14772
        published: '41430'
        protocol: tcp
      - target: 14773
        published: '41433'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-managed-cartesian-ports-cartesian-modify-add-composite-helper-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923205535-1808238-update-legacy-managed-cartesian-ports-cartesian-modify-add-composite-helper-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
    ports:
      - target: 14774
        published: '41435'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.legacy-managed-cartesian-ports-cartesian-modify-add-composite-helper-to-main
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-managed-cartesian-ports-cartesian-modify-add-composite-helper-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-managed-cartesian ports cartesian-modify-add composite helper-to-main
    zh_CN: E2E legacy-managed-cartesian ports cartesian-modify-add composite helper-to-main
  port_map: '19143'
  version: 1.1.0
  scheme: http
  index: /
