name: zimaos-e2e-legacy-unmanaged-environment-local-delete-upstream-unchanged-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    container_name: zimaos-e2e-legacy-unmanaged-environment-local-delete-upstream-unchanged-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260922115813-1453972-update-legacy-unmanaged-environment-local-delete-upstream-unchanged-single-main-to-main
      E2E_CASE_023_MAIN_A: baseline-a
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18223'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-environment-local-delete-upstream-unchanged-single-main-to-main
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-environment-local-delete-upstream-unchanged-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged environment local-delete-upstream-unchanged single main-to-main
    zh_CN: E2E legacy-unmanaged environment local-delete-upstream-unchanged single main-to-main
  port_map: '18223'
  version: 1.1.0
  scheme: http
  index: /
