name: zimaos-e2e-legacy-two-stage-cartesian-ports-cartesian-modify-modify-composite-main-to-helper
services:
  web:
    image: traefik/whoami:v1.11.0
    container_name: zimaos-e2e-legacy-two-stage-cartesian-ports-cartesian-modify-modify-composite-main-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920141525-846597-update-legacy-two-stage-cartesian-ports-cartesian-modify-modify-composite-main-to-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19466'
        protocol: tcp
      - target: 16064
        published: '44660'
        protocol: tcp
      - target: 16065
        published: '44662'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-two-stage-cartesian-ports-cartesian-modify-modify-composite-main-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920141525-846597-update-legacy-two-stage-cartesian-ports-cartesian-modify-modify-composite-main-to-helper-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
    ports:
      - target: 16066
        published: '44665'
        protocol: tcp
      - target: 16067
        published: '44668'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.legacy-two-stage-cartesian-ports-cartesian-modify-modify-composite-main-to-helper
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-two-stage-cartesian-ports-cartesian-modify-modify-composite-main-to-helper/assets/icon.svg
  title:
    en_US: E2E legacy-two-stage-cartesian ports cartesian-modify-modify composite main-to-helper
    zh_CN: E2E legacy-two-stage-cartesian ports cartesian-modify-modify composite main-to-helper
  port_map: '19466'
  version: 1.1.0
  scheme: http
  index: /
