name: homebridge
version: '2'
services:
  homebridge:
    image: homebridge/homebridge@sha256:d4f3579fc09c8d43d6956c8c970351f510096b9d990c53280d2c27c1e77bfbef
    restart: always
    network_mode: host
    volumes:
    - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '1'
x-casaos:
  main: homebridge
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/homebridge/assets/icon.png
  title:
    en_US: Homebridge
  index: /
  port_map: '8581'
  version: latest
