name: homebridge
version: '2'
services:
  homebridge:
    image: homebridge/homebridge@sha256:540484a2f15b61184804daeacc705dc86d3db811182d4b46d3deb524647ff29a
    restart: always
    network_mode: host
    volumes:
    - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '1'
x-casaos:
  main: homebridge
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/homebridge/assets/icon.png
  title:
    en_US: Homebridge
  index: /
  port_map: '8581'
  version: latest
