name: homebridge
version: '2'
services:
  homebridge:
    image: homebridge/homebridge@sha256:77c685a40911b3b95448f3550be0c8b94cd7b4e66daecc1cc39a8285be75b245
    restart: always
    network_mode: host
    volumes:
    - /DATA/AppData/$AppID/config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10mb
        max-file: '1'
x-casaos:
  main: homebridge
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/homebridge/assets/icon.png
  title:
    en_US: Homebridge
  index: /
  port_map: '8581'
  version: latest
