name: zimaos-e2e-environment-modify-different-single
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:4f90b33ddca9c4d4f06527070d6e503b16d71016edea036842be2a84e60c91cb
    container_name: zimaos-e2e-environment-modify-different-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260918034101-284415-update-environment-modify-different-single
      E2E_CASE_007_A: baseline-a
      E2E_CASE_007_B: upstream-b
    restart: unless-stopped
    ports:
      - target: 80
        published: '18207'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.environment-modify-different-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.environment-modify-different-single/assets/icon.svg
  title:
    en_US: E2E Environment Modify-Different Single
    zh_CN: E2E Environment Modify-Different Single
  port_map: '18207'
  version: 1.1.0
