name: zimaos-e2e-legacy-unmanaged-ports-add-different-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.11.0
    container_name: zimaos-e2e-legacy-unmanaged-ports-add-different-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920033520-673872-update-legacy-unmanaged-ports-add-different-single-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18203'
        protocol: tcp
      - target: 10013
        published: '30027'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-ports-add-different-single-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-ports-add-different-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged ports add-different single main-to-main
    zh_CN: E2E legacy-unmanaged ports add-different single main-to-main
  port_map: '18203'
  version: 1.1.0
  scheme: http
  index: /
