name: nginx
services:
  nginx:
    cpu_shares: 90
    command:
      - nginx
      - -g
      - daemon off;
    container_name: nginx
    deploy:
      resources:
        limits:
          memory: 15703M
    environment:
      - NGINX_VERSION=1.25.2
      - NJS_VERSION=0.8.0
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PKG_RELEASE=1~bookworm
    image: nginx:1.25.2
    ports:
      - target: 80
        published: "8080"
        protocol: tcp
    restart: unless-stopped
    x-casaos:
      envs:
        - container: PATH
          description:
            en_us: ""
        - container: NGINX_VERSION
          description:
            en_us: ""
        - container: NJS_VERSION
          description:
            en_us: ""
        - container: PKG_RELEASE
          description:
            en_us: ""
      image: ""
    volumes: []
    devices: []
    cap_add: []
    network_mode: default
    privileged: false
x-casaos:
  architectures:
    - amd64
  author: CasaOS User
  category: unknown
  description:
    en_us: ""
  developer: unknown
  hostname: ""
  icon: ""
  image: null
  index: /
  is_uncontrolled: false
  main: nginx
  port_map: "8080"
  scheme: http
  store_app_id: nginx
  tagline:
    en_us: This is a compose app converted from a legacy app (CasaOS v0.4.3 or
      earlier)
  thumbnail: ""
  tips:
    custom: This is a compose app converted from a legacy app (CasaOS v0.4.3 or
      earlier)
  title:
    custom: nginx
    en_us: nginx
