name: zimaos-e2e-ports-local-unchanged-upstream-delete-single
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-ports-local-unchanged-upstream-delete-single-web
    environment:
      ZIMAOS_E2E_BASELINE: 20260917103026-76552-update-ports-local-unchanged-upstream-delete-single
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    ports:
      - target: 10058
        published: '30116'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.ports-local-unchanged-upstream-delete-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.ports-local-unchanged-upstream-delete-single/assets/icon.svg
  title:
    en_US: E2E Ports Local-Unchanged-Upstream-Delete Single
    zh_CN: E2E Ports Local-Unchanged-Upstream-Delete Single
  port_map: '18229'
  version: 1.0.0
