name: zimaos-e2e-upgrade-single
services:
  web:
    image: traefik/whoami:v1.11.0
    container_name: zimaos-e2e-upgrade-single-web
    restart: always
    ports:
      - target: 80
        published: '18101'
        protocol: tcp
      - target: 80
        published: '18121'
        protocol: tcp
    environment:
      ZIMAOS_E2E_BASELINE: 20260917080955-49980-update-single
      E2E_SHARED: upstream-loses
      E2E_LOCAL_DELETE_UPSTREAM_MODIFY: upstream-value
      E2E_LOCAL_EMPTY_UPSTREAM_VALUE: upstream-value
      E2E_LOCAL_VALUE_UPSTREAM_EMPTY: ''
      E2E_BOTH_EMPTY: ''
      E2E_UPSTREAM_ONLY: upstream-value
      E2E_UPSTREAM_ADDED: upstream-value
      E2E_BOTH_ADD_SAME: upstream-loses
      E2E_DIFFERENT_UPSTREAM: upstream-value
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
      - type: bind
        source: /DATA/AppData/zimaos-e2e-upgrade-single/e2e-upstream
        target: /e2e-local
    command:
      - --port=80
      - --name=upstream-single
x-casaos:
  id: org.zimaos.e2e.upgrade-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.upgrade-single/assets/icon.svg
  title:
    en_US: E2E Upgrade Single
    zh_CN: E2E Upgrade Single
  port_map: '18101'
  version: 1.1.0
