name: zimaos-e2e-command-modify-different-composite
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-command-modify-different-composite-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260918055056-316649-update-command-modify-different-composite
    restart: unless-stopped
    ports:
      - target: 80
        published: '18208'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
      - --name=baseline
  helper:
    image: alpine:3.20
    container_name: zimaos-e2e-command-modify-different-composite-helper
    network_mode: bridge
    restart: unless-stopped
    environment:
      E2E_SECONDARY_BASELINE: 20260918055056-316649-update-command-modify-different-composite
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
x-casaos:
  id: org.zimaos.e2e.command-modify-different-composite
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.command-modify-different-composite/assets/icon.svg
  title:
    en_US: E2E Command Modify-Different Composite
    zh_CN: E2E Command Modify-Different Composite
  port_map: '18208'
  version: 1.0.0
