name: zimaos-e2e-legacy-two-stage-cartesian-command-cartesian-delete-delete-composite-main-to-main-r2-p19613
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-two-stage-cartesian-command-cartesian-delete-delete-composite-main-to-main-r2-p19613-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20261004112300-1470643-update-legacy-two-stage-cartesian-command-cartesian-delete-delete-composite-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19613'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
      - --name=baseline-local-main-1413
      - --verbose=false
  helper:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-two-stage-cartesian-command-cartesian-delete-delete-composite-main-to-main-r2-p19613-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20261004112300-1470643-update-legacy-two-stage-cartesian-command-cartesian-delete-delete-composite-main-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
      - --name=baseline-local-helper-1413
      - --verbose=false
x-casaos:
  id: org.zimaos.e2e.legacy-two-stage-cartesian-command-cartesian-delete-delete-composite-main-to-main.r2.p19613
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-two-stage-cartesian-command-cartesian-delete-delete-composite-main-to-main.r2.p19613/assets/icon.svg
  title:
    en_US: E2E legacy-two-stage-cartesian command cartesian-delete-delete composite main-to-main
    zh_CN: E2E legacy-two-stage-cartesian command cartesian-delete-delete composite main-to-main
  port_map: '19613'
  version: 1.0.0
  scheme: http
  index: /
