name: zimaos-e2e-restart-delete-same-single
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-restart-delete-same-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917200829-201158-update-restart-delete-same-single
    ports:
      - target: 80
        published: '18209'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    restart: unless-stopped
x-casaos:
  id: org.zimaos.e2e.restart-delete-same-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.restart-delete-same-single/assets/icon.svg
  title:
    en_US: E2E Restart Delete-Same Single
    zh_CN: E2E Restart Delete-Same Single
  port_map: '18209'
  version: 1.0.0
