name: zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-modify-composite-helper-to-helper
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-modify-composite-helper-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920121320-814225-update-legacy-unmanaged-cartesian-volumes-cartesian-modify-modify-composite-helper-to-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-modify-composite-helper-to-helper/cart-baseline-local
        target: /e2e-cart-0692-local
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-modify-composite-helper-to-helper/cart-baseline-upstream
        target: /e2e-cart-0692-upstream
    ports:
      - target: 80
        published: '18892'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-modify-composite-helper-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920121320-814225-update-legacy-unmanaged-cartesian-volumes-cartesian-modify-modify-composite-helper-to-helper-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-modify-composite-helper-to-helper/cart-baseline-local-helper
        target: /e2e-cart-0692-local-helper
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-unmanaged-cartesian-volumes-cartesian-modify-modify-composite-helper-to-helper/cart-baseline-upstream-helper
        target: /e2e-cart-0692-upstream-helper
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-cartesian-volumes-cartesian-modify-modify-composite-helper-to-helper
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-cartesian-volumes-cartesian-modify-modify-composite-helper-to-helper/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged-cartesian volumes cartesian-modify-modify composite helper-to-helper
    zh_CN: E2E legacy-unmanaged-cartesian volumes cartesian-modify-modify composite helper-to-helper
  port_map: '18892'
  version: 1.0.0
  scheme: http
  index: /
