name: zimaos-e2e-legacy-managed-command-local-modify-upstream-unchanged-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-managed-command-local-modify-upstream-unchanged-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923192050-1779572-update-legacy-managed-command-local-modify-upstream-unchanged-single-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18413'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
      - --name=baseline-main
x-casaos:
  id: org.zimaos.e2e.legacy-managed-command-local-modify-upstream-unchanged-single-main-to-main
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-managed-command-local-modify-upstream-unchanged-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-managed command local-modify-upstream-unchanged single main-to-main
    zh_CN: E2E legacy-managed command local-modify-upstream-unchanged single main-to-main
  port_map: '18413'
  version: 1.0.0
  scheme: http
  index: /
