name: zimaos-e2e-command-add-different-single
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:c899811bc4a1f63a1273c612e15f1bea6514a19c7b08143dbbdef3e8f882c38d
    container_name: zimaos-e2e-command-add-different-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917183130-181889-update-command-add-different-single
    restart: unless-stopped
    ports:
      - target: 80
        published: '18203'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
x-casaos:
  id: org.zimaos.e2e.command-add-different-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.command-add-different-single/assets/icon.svg
  title:
    en_US: E2E Command Add-Different Single
    zh_CN: E2E Command Add-Different Single
  port_map: '18203'
  version: 1.0.0
