name: zimaos-e2e-environment-modify-same-single
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-environment-modify-same-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917123037-97265-update-environment-modify-same-single
      E2E_CASE_005_A: baseline-a
    restart: unless-stopped
    ports:
      - target: 80
        published: '18205'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.environment-modify-same-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.environment-modify-same-single/assets/icon.svg
  title:
    en_US: E2E Environment Modify-Same Single
    zh_CN: E2E Environment Modify-Same Single
  port_map: '18205'
  version: 1.0.0
