name: v2raya
services:
  v2raya:
    image: mzz2017/v2raya:v2.4.19@sha256:44293ea84364b650ac7fa2208bb9152d3806f99f9aed9eae7f0da92e3eaecf72
    container_name: v2raya
    deploy:
      resources:
        reservations:
          memory: 128M
    environment:
      ZIMAOS_E2E_UPGRADE_MARKER: zimaos-e2e-20260915072700-v2raya
    ports:
      - target: 2017
        published: "12017"
        protocol: tcp
    command:
      - --log-level
      - info
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - type: bind
        source: /lib/modules
        target: /lib/modules
        read_only: true
      - type: bind
        source: /etc/resolv.conf
        target: /etc/resolv.conf
      - type: bind
        source: /DATA/AppData/$AppID
        target: /etc/v2raya
      - type: bind
        source: /DATA/AppData/$AppID/e2e-upgrade
        target: /zimaos-e2e-upgrade/v2raya
x-casaos:
  id: org.icewhale.v2raya
  main: v2raya
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.icewhale.v2raya/assets/icon.svg
  scheme: http
  port_map: "2017"
  index: /
  title:
    en_US: V2rayA
  version: "2.4.19"
