name: zimaos-e2e-legacy-unmanaged-environment-modify-same-composite-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:f1c59fb1677f4711290c320d288e182adad7b84326d71cf5fb883893b07cd23d
    container_name: zimaos-e2e-legacy-unmanaged-environment-modify-same-composite-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-unmanaged-environment-modify-same-composite-main-to-main
      E2E_CASE_006_MAIN_A: baseline-a
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18206'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: alpine:3.20@sha256:37753b2965043543542cd9d48cba044151052ca14fa72e6cbec4edf2a1490599
    container_name: zimaos-e2e-legacy-unmanaged-environment-modify-same-composite-main-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-unmanaged-environment-modify-same-composite-main-to-main-helper
      E2E_CASE_006_HELPER_A: baseline-a
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-environment-modify-same-composite-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-environment-modify-same-composite-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged environment modify-same composite main-to-main
    zh_CN: E2E legacy-unmanaged environment modify-same composite main-to-main
  port_map: '18206'
  version: 1.0.0
  scheme: http
  index: /
