name: zimaos-e2e-ports-modify-different-composite
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    container_name: zimaos-e2e-ports-modify-different-composite-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917140034-116715-update-ports-modify-different-composite
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    ports:
      - target: 10016
        published: '30032'
        protocol: tcp
      - target: 10017
        published: '30035'
        protocol: tcp
  helper:
    image: alpine:3.20@sha256:45e09956dc667c5eff3583c9d94830261fb1ca0be10a0a7db36266edf5de9e1d
    container_name: zimaos-e2e-ports-modify-different-composite-helper
    network_mode: bridge
    restart: unless-stopped
    environment:
      E2E_SECONDARY_BASELINE: 20260917140034-116715-update-ports-modify-different-composite
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
x-casaos:
  id: org.zimaos.e2e.ports-modify-different-composite
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.ports-modify-different-composite/assets/icon.svg
  title:
    en_US: E2E Ports Modify-Different Composite
    zh_CN: E2E Ports Modify-Different Composite
  port_map: '18208'
  version: 1.1.0
