name: zimaos-e2e-legacy-unmanaged-environment-local-delete-upstream-modify-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:f1c59fb1677f4711290c320d288e182adad7b84326d71cf5fb883893b07cd23d
    container_name: zimaos-e2e-legacy-unmanaged-environment-local-delete-upstream-modify-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921171621-1205145-update-legacy-unmanaged-environment-local-delete-upstream-modify-single-main-to-main
      E2E_CASE_011_MAIN_A: baseline-a
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18211'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-environment-local-delete-upstream-modify-single-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-environment-local-delete-upstream-modify-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged environment local-delete-upstream-modify single main-to-main
    zh_CN: E2E legacy-unmanaged environment local-delete-upstream-modify single main-to-main
  port_map: '18211'
  version: 1.0.0
  scheme: http
  index: /
