name: zimaos-e2e-image-single-versionless-srcaudit-nodrift-1001a-p18111
services:
  web:
    image: traefik/whoami:latest
    container_name: zimaos-e2e-image-single-versionless-srcaudit-nodrift-1001a-p18111-web
    restart: unless-stopped
    ports:
      - target: 80
        published: '18111'
        protocol: tcp
    environment:
      ZIMAOS_E2E_BASELINE: 20261001205118-994857-image-single-versionless
      E2E_SHARED: baseline
      E2E_LOCAL_DELETE_UPSTREAM_MODIFY: baseline
      E2E_LOCAL_KEEP_UPSTREAM_DELETE: baseline
      E2E_LOCAL_EMPTY_UPSTREAM_VALUE: baseline
      E2E_LOCAL_VALUE_UPSTREAM_EMPTY: baseline
      E2E_BOTH_EMPTY: baseline
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.image-single-versionless.srcaudit-nodrift-1001a.p18111
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.image-single-versionless.srcaudit-nodrift-1001a.p18111/assets/icon.svg
  title:
    en_US: E2E Image Single Without Version
    zh_CN: E2E Image Single Without Version
  port_map: '18111'
  version: 1.0.0
  scheme: http
  index: /
