name: zimaos-e2e-legacy-two-stage-cartesian-command-cartesian-add-modify-composite-helper-to-main
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    container_name: zimaos-e2e-legacy-two-stage-cartesian-command-cartesian-add-modify-composite-helper-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920141525-846597-update-legacy-two-stage-cartesian-command-cartesian-add-modify-composite-helper-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19579'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
      - --verbose=true
  helper:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-two-stage-cartesian-command-cartesian-add-modify-composite-helper-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920141525-846597-update-legacy-two-stage-cartesian-command-cartesian-add-modify-composite-helper-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
      - --verbose=false
x-casaos:
  id: org.zimaos.e2e.legacy-two-stage-cartesian-command-cartesian-add-modify-composite-helper-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-two-stage-cartesian-command-cartesian-add-modify-composite-helper-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-two-stage-cartesian command cartesian-add-modify composite helper-to-main
    zh_CN: E2E legacy-two-stage-cartesian command cartesian-add-modify composite helper-to-main
  port_map: '19579'
  version: 1.1.0
  scheme: http
  index: /
