name: zimaos-e2e-legacy-two-stage-cartesian-restart-cartesian-unchanged-modify-composite-helper-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:c899811bc4a1f63a1273c612e15f1bea6514a19c7b08143dbbdef3e8f882c38d
    container_name: zimaos-e2e-legacy-two-stage-cartesian-restart-cartesian-unchanged-modify-composite-helper-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921103234-1111027-update-legacy-two-stage-cartesian-restart-cartesian-unchanged-modify-composite-helper-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19691'
        protocol: tcp
    command:
      - --port=80
    restart: unless-stopped
  helper:
    image: traefik/whoami:v1.10.3@sha256:c899811bc4a1f63a1273c612e15f1bea6514a19c7b08143dbbdef3e8f882c38d
    container_name: zimaos-e2e-legacy-two-stage-cartesian-restart-cartesian-unchanged-modify-composite-helper-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921103234-1111027-update-legacy-two-stage-cartesian-restart-cartesian-unchanged-modify-composite-helper-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    command:
      - --port=80
    restart: unless-stopped
x-casaos:
  id: org.zimaos.e2e.legacy-two-stage-cartesian-restart-cartesian-unchanged-modify-composite-helper-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-two-stage-cartesian-restart-cartesian-unchanged-modify-composite-helper-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-two-stage-cartesian restart cartesian-unchanged-modify composite helper-to-main
    zh_CN: E2E legacy-two-stage-cartesian restart cartesian-unchanged-modify composite helper-to-main
  port_map: '19691'
  version: 1.0.0
  scheme: http
  index: /
