name: zimaos-e2e-volumes-local-empty-upstream-value-single
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:4f90b33ddca9c4d4f06527070d6e503b16d71016edea036842be2a84e60c91cb
    container_name: zimaos-e2e-volumes-local-empty-upstream-value-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917144513-127766-update-volumes-local-empty-upstream-value-single
    restart: unless-stopped
    ports:
      - target: 80
        published: '18215'
        protocol: tcp
    command:
      - --port=80
    volumes:
      - type: bind
        source: /DATA/AppData/zimaos-e2e-volumes-local-empty-upstream-value-single/case-upstream-a
        target: /e2e-case-a
x-casaos:
  id: org.zimaos.e2e.volumes-local-empty-upstream-value-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.volumes-local-empty-upstream-value-single/assets/icon.svg
  title:
    en_US: E2E Volumes Local-Empty-Upstream-Value Single
    zh_CN: E2E Volumes Local-Empty-Upstream-Value Single
  port_map: '18215'
  version: 1.1.0
