name: zimaos-e2e-native-composite-update-scope-environment-image-helper-only-config-main-only
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-native-composite-update-scope-environment-image-helper-only-config-main-only-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923192050-1779572-update-native-composite-update-scope-environment-image-helper-only-config-main-only
      E2E_CASE_1794_MAIN_A: upstream-a
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19994'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: alpine:3.21@sha256:0a7ed0d449b9318548e66674610d757de19b7645759f74b587b610b59d6b43fd
    container_name: zimaos-e2e-native-composite-update-scope-environment-image-helper-only-config-main-only-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923192050-1779572-update-native-composite-update-scope-environment-image-helper-only-config-main-only-helper
      E2E_CASE_1794_HELPER_A: baseline-a
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
x-casaos:
  id: org.zimaos.e2e.native-composite-update-scope-environment-image-helper-only-config-main-only
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.native-composite-update-scope-environment-image-helper-only-config-main-only/assets/icon.svg
  title:
    en_US: E2E Update Scope environment image-helper-only config-main-only
    zh_CN: E2E Update Scope environment image-helper-only config-main-only
  port_map: '19994'
  version: 1.1.0
  scheme: http
  index: /
