name: zimaos-e2e-legacy-two-stage-cartesian-environment-cartesian-add-modify-composite-main-to-helper
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-two-stage-cartesian-environment-cartesian-add-modify-composite-main-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-two-stage-cartesian-environment-cartesian-add-modify-composite-main-to-helper
      E2E_CART_1186_MAIN: baseline
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19386'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-two-stage-cartesian-environment-cartesian-add-modify-composite-main-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-two-stage-cartesian-environment-cartesian-add-modify-composite-main-to-helper-helper
      E2E_CART_1186_HELPER: baseline
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-two-stage-cartesian-environment-cartesian-add-modify-composite-main-to-helper
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-two-stage-cartesian-environment-cartesian-add-modify-composite-main-to-helper/assets/icon.svg
  title:
    en_US: E2E legacy-two-stage-cartesian environment cartesian-add-modify composite main-to-helper
    zh_CN: E2E legacy-two-stage-cartesian environment cartesian-add-modify composite main-to-helper
  port_map: '19386'
  version: 1.0.0
  scheme: http
  index: /
