name: zimaos-e2e-legacy-managed-cartesian-ports-cartesian-add-delete-composite-main-to-helper
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-managed-cartesian-ports-cartesian-add-delete-composite-main-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-managed-cartesian-ports-cartesian-add-delete-composite-main-to-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19134'
        protocol: tcp
      - target: 12868
        published: '37604'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-managed-cartesian-ports-cartesian-add-delete-composite-main-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-managed-cartesian-ports-cartesian-add-delete-composite-main-to-helper-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
    ports:
      - target: 12869
        published: '37607'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.legacy-managed-cartesian-ports-cartesian-add-delete-composite-main-to-helper
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-managed-cartesian-ports-cartesian-add-delete-composite-main-to-helper/assets/icon.svg
  title:
    en_US: E2E legacy-managed-cartesian ports cartesian-add-delete composite main-to-helper
    zh_CN: E2E legacy-managed-cartesian ports cartesian-add-delete composite main-to-helper
  port_map: '19134'
  version: 1.0.0
  scheme: http
  index: /
