name: zimaos-e2e-ports-add-different-single
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:f1c59fb1677f4711290c320d288e182adad7b84326d71cf5fb883893b07cd23d
    container_name: zimaos-e2e-ports-add-different-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917133559-110860-update-ports-add-different-single
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    ports: []
x-casaos:
  id: org.zimaos.e2e.ports-add-different-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.ports-add-different-single/assets/icon.svg
  title:
    en_US: E2E Ports Add-Different Single
    zh_CN: E2E Ports Add-Different Single
  port_map: '18203'
  version: 1.0.0
