name: zimaos-e2e-legacy-unmanaged-cartesian-ports-cartesian-delete-delete-composite-helper-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-ports-cartesian-delete-delete-composite-helper-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920141525-846597-update-legacy-unmanaged-cartesian-ports-cartesian-delete-delete-composite-helper-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18847'
        protocol: tcp
      - target: 13588
        published: '38470'
        protocol: tcp
      - target: 13589
        published: '38472'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-ports-cartesian-delete-delete-composite-helper-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920141525-846597-update-legacy-unmanaged-cartesian-ports-cartesian-delete-delete-composite-helper-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - --port=80
    ports:
      - target: 13590
        published: '38475'
        protocol: tcp
      - target: 13591
        published: '38477'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-cartesian-ports-cartesian-delete-delete-composite-helper-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-cartesian-ports-cartesian-delete-delete-composite-helper-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged-cartesian ports cartesian-delete-delete composite helper-to-main
    zh_CN: E2E legacy-unmanaged-cartesian ports cartesian-delete-delete composite helper-to-main
  port_map: '18847'
  version: 1.0.0
  scheme: http
  index: /
