name: zimaos-e2e-native-composite-update-scope-restart-image-main-and-helper-config-helper-only
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:4f90b33ddca9c4d4f06527070d6e503b16d71016edea036842be2a84e60c91cb
    container_name: zimaos-e2e-native-composite-update-scope-restart-image-main-and-helper-config-helper-only-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923192050-1779572-update-native-composite-update-scope-restart-image-main-and-helper-config-helper-only
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '20034'
        protocol: tcp
    command:
      - --port=80
    restart: unless-stopped
  helper:
    image: alpine:3.21@sha256:3c81aa9a3d770b316568f4499e30461a5cd3fbd7180bd89e28e34894c7845832
    container_name: zimaos-e2e-native-composite-update-scope-restart-image-main-and-helper-config-helper-only-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923192050-1779572-update-native-composite-update-scope-restart-image-main-and-helper-config-helper-only-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
    restart: always
x-casaos:
  id: org.zimaos.e2e.native-composite-update-scope-restart-image-main-and-helper-config-helper-only
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.native-composite-update-scope-restart-image-main-and-helper-config-helper-only/assets/icon.svg
  title:
    en_US: E2E Update Scope restart image-main-and-helper config-helper-only
    zh_CN: E2E Update Scope restart image-main-and-helper config-helper-only
  port_map: '20034'
  version: 1.1.0
  scheme: http
  index: /
