name: zimaos-e2e-ports-local-delete-upstream-modify-single
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:4f90b33ddca9c4d4f06527070d6e503b16d71016edea036842be2a84e60c91cb
    container_name: zimaos-e2e-ports-local-delete-upstream-modify-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917140034-116715-update-ports-local-delete-upstream-modify-single
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    ports:
      - target: 10022
        published: '30047'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.ports-local-delete-upstream-modify-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.ports-local-delete-upstream-modify-single/assets/icon.svg
  title:
    en_US: E2E Ports Local-Delete-Upstream-Modify Single
    zh_CN: E2E Ports Local-Delete-Upstream-Modify Single
  port_map: '18211'
  version: 1.1.0
