name: zimaos-e2e-native-composite-cross-restart-delete-same-composite-main-to-helper
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-native-composite-cross-restart-delete-same-composite-main-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920131236-829500-update-native-composite-cross-restart-delete-same-composite-main-to-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18717'
        protocol: tcp
    command:
      - --port=80
    restart: unless-stopped
  helper:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-native-composite-cross-restart-delete-same-composite-main-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920131236-829500-update-native-composite-cross-restart-delete-same-composite-main-to-helper-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    command:
      - --port=80
    restart: unless-stopped
x-casaos:
  id: org.zimaos.e2e.native-composite-cross-restart-delete-same-composite-main-to-helper
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.native-composite-cross-restart-delete-same-composite-main-to-helper/assets/icon.svg
  title:
    en_US: E2E native-composite-cross restart delete-same composite main-to-helper
    zh_CN: E2E native-composite-cross restart delete-same composite main-to-helper
  port_map: '18717'
  version: 1.0.0
  scheme: http
  index: /
