name: zimaos-e2e-legacy-previous-base-versionless-target-restart-cartesian-modify-add-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-previous-base-versionless-target-restart-cartesian-modify-add-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260922123745-1463104-update-legacy-previous-base-versionless-target-restart-cartesian-modify-add-single-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19813'
        protocol: tcp
    command:
      - --port=80
    restart: unless-stopped
x-casaos:
  id: org.zimaos.e2e.legacy-previous-base-versionless-target-restart-cartesian-modify-add-single-main-to-main
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-previous-base-versionless-target-restart-cartesian-modify-add-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-previous-base-versionless-target restart cartesian-modify-add single main-to-main
    zh_CN: E2E legacy-previous-base-versionless-target restart cartesian-modify-add single main-to-main
  port_map: '19813'
  version: 1.0.0
  scheme: http
  index: /
