name: zimaos-e2e-command-modify-different-single
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    container_name: zimaos-e2e-command-modify-different-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917185928-187279-update-command-modify-different-single
    restart: unless-stopped
    ports:
      - target: 80
        published: '18207'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
      - --name=upstream
x-casaos:
  id: org.zimaos.e2e.command-modify-different-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.command-modify-different-single/assets/icon.svg
  title:
    en_US: E2E Command Modify-Different Single
    zh_CN: E2E Command Modify-Different Single
  port_map: '18207'
  version: 1.1.0
