name: zimaos-e2e-legacy-two-stage-edit-environment-local-modify-upstream-unchanged-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-legacy-two-stage-edit-environment-local-modify-upstream-unchanged-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923205535-1808238-update-legacy-two-stage-edit-environment-local-modify-upstream-unchanged-single-main-to-main
      E2E_CASE_1721_MAIN_A: baseline-a
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19921'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-two-stage-edit-environment-local-modify-upstream-unchanged-single-main-to-main
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-two-stage-edit-environment-local-modify-upstream-unchanged-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-two-stage-edit environment local-modify-upstream-unchanged single main-to-main
    zh_CN: E2E legacy-two-stage-edit environment local-modify-upstream-unchanged single main-to-main
  port_map: '19921'
  version: 1.0.0
  scheme: http
  index: /
