name: memos
services:
  memos:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
      E2E_UPSTREAM_ONLY: upstream-value
      E2E_SHARED: upstream-loses
    image: neosmemo/memos:0.30.0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 5230
        published: '5230'
        protocol: tcp
      - target: 25231
        published: '25231'
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/memos/memos
        target: /var/opt/memos
      - type: bind
        source: /DATA/AppData/memos/e2e-upstream
        target: /e2e-upstream
    container_name: memos
    command:
      - --port
      - '5230'
x-casaos:
  id: org.icewhale.memos
  main: memos
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.icewhale.memos/assets/icon.svg
  title:
    en_US: Memos
  port_map: '5230'
  version: 0.30.0
