name: zimaos-e2e-legacy-two-stage-cartesian-volumes-cartesian-unchanged-modify-composite-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-two-stage-cartesian-volumes-cartesian-unchanged-modify-composite-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923205535-1808238-update-legacy-two-stage-cartesian-volumes-cartesian-unchanged-modify-composite-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-two-stage-cartesian-volumes-cartesian-unchanged-modify-composite-main-to-main/cart-baseline-upstream
        target: /e2e-cart-1361-upstream
    ports:
      - target: 80
        published: '19561'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-two-stage-cartesian-volumes-cartesian-unchanged-modify-composite-main-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923205535-1808238-update-legacy-two-stage-cartesian-volumes-cartesian-unchanged-modify-composite-main-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-two-stage-cartesian-volumes-cartesian-unchanged-modify-composite-main-to-main/cart-baseline-upstream-helper
        target: /e2e-cart-1361-upstream-helper
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-two-stage-cartesian-volumes-cartesian-unchanged-modify-composite-main-to-main
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-two-stage-cartesian-volumes-cartesian-unchanged-modify-composite-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-two-stage-cartesian volumes cartesian-unchanged-modify composite main-to-main
    zh_CN: E2E legacy-two-stage-cartesian volumes cartesian-unchanged-modify composite main-to-main
  port_map: '19561'
  version: 1.0.0
  scheme: http
  index: /
