name: netbird
services:
  netbird:
    image: netbirdio/netbird:0.78.1@sha256:31f4cc5d1501d2149bf451f02af1c91e909cd124c0a5190458b3541d294f4de4
    container_name: netbird
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    deploy:
      resources:
        reservations:
          memory: 128M
    environment:
      NB_SETUP_KEY: ""
      NB_MANAGEMENT_URL: ""
      NB_HOSTNAME: "Zima"
      NB_ENABLE_SSH_ROOT: "true"
      NB_ALLOW_SERVER_SSH: "true"
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /var/lib/netbird
x-casaos:
  id: org.icewhale.netbird
  main: netbird
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.icewhale.netbird/assets/icon.svg
  scheme: "https"
  port_map: ""
  index: /
  title:
    en_US: NetBird
  version: "0.78.1"
