name: zimaos-e2e-restart-modify-same-single
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:9564f83910c98c3bea640803d8014b5c586b4bd556906d1afab21c7e7f1e4d4c
    container_name: zimaos-e2e-restart-modify-same-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260918063303-327707-update-restart-modify-same-single
    ports:
      - target: 80
        published: '18205'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    restart: always
x-casaos:
  id: org.zimaos.e2e.restart-modify-same-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.restart-modify-same-single/assets/icon.svg
  title:
    en_US: E2E Restart Modify-Same Single
    zh_CN: E2E Restart Modify-Same Single
  port_map: '18205'
  version: 1.1.0
