name: zimaos-e2e-volumes-delete-same-single
services:
  web:
    image: traefik/whoami:v1.11.0
    container_name: zimaos-e2e-volumes-delete-same-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917144513-127766-update-volumes-delete-same-single
    restart: unless-stopped
    ports:
      - target: 80
        published: '18209'
        protocol: tcp
    command:
      - --port=80
    volumes: []
x-casaos:
  id: org.zimaos.e2e.volumes-delete-same-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.volumes-delete-same-single/assets/icon.svg
  title:
    en_US: E2E Volumes Delete-Same Single
    zh_CN: E2E Volumes Delete-Same Single
  port_map: '18209'
  version: 1.1.0
