name: zimaos-e2e-legacy-unmanaged-volumes-modify-different-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:9564f83910c98c3bea640803d8014b5c586b4bd556906d1afab21c7e7f1e4d4c
    container_name: zimaos-e2e-legacy-unmanaged-volumes-modify-different-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920050041-700123-update-legacy-unmanaged-volumes-modify-different-single-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-unmanaged-volumes-modify-different-single-main-to-main/case-base-a
        target: /e2e-case-a
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-unmanaged-volumes-modify-different-single-main-to-main/case-upstream-b
        target: /e2e-case-b
    ports:
      - target: 80
        published: '18207'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-volumes-modify-different-single-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-volumes-modify-different-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged volumes modify-different single main-to-main
    zh_CN: E2E legacy-unmanaged volumes modify-different single main-to-main
  port_map: '18207'
  version: 1.1.0
  scheme: http
  index: /
