name: zimaos-e2e-legacy-previous-base-versionless-target-environment-cartesian-delete-unchanged-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-previous-base-versionless-target-environment-cartesian-delete-unchanged-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921141411-1168127-update-legacy-previous-base-versionless-target-environment-cartesian-delete-unchanged-single-main-to-main
      E2E_CART_1572_MAIN_LOCAL: baseline-local
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19772'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-previous-base-versionless-target-environment-cartesian-delete-unchanged-single-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-previous-base-versionless-target-environment-cartesian-delete-unchanged-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-previous-base-versionless-target environment cartesian-delete-unchanged single main-to-main
    zh_CN: E2E legacy-previous-base-versionless-target environment cartesian-delete-unchanged single main-to-main
  port_map: '19772'
  version: 1.0.0
  scheme: http
  index: /
