name: zimaos-e2e-native-ports-local-unchanged-upstream-delete-composite-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-native-ports-local-unchanged-upstream-delete-composite-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-native-ports-local-unchanged-upstream-delete-composite-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18482'
        protocol: tcp
      - target: 11128
        published: '32256'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: alpine:3.20
    container_name: zimaos-e2e-native-ports-local-unchanged-upstream-delete-composite-main-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-native-ports-local-unchanged-upstream-delete-composite-main-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
    ports:
      - target: 11130
        published: '32260'
        protocol: tcp
x-casaos:
  id: org.zimaos.e2e.native-ports-local-unchanged-upstream-delete-composite-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.native-ports-local-unchanged-upstream-delete-composite-main-to-main/assets/icon.svg
  title:
    en_US: E2E native ports local-unchanged-upstream-delete composite main-to-main
    zh_CN: E2E native ports local-unchanged-upstream-delete composite main-to-main
  port_map: '18482'
  version: 1.0.0
  scheme: http
  index: /
