name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-delete-add-composite-main-to-helper
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:c899811bc4a1f63a1273c612e15f1bea6514a19c7b08143dbbdef3e8f882c38d
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-delete-add-composite-main-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-unmanaged-cartesian-restart-cartesian-delete-add-composite-main-to-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19030'
        protocol: tcp
    command:
      - --port=80
    restart: unless-stopped
  helper:
    image: traefik/whoami:v1.10.3@sha256:c899811bc4a1f63a1273c612e15f1bea6514a19c7b08143dbbdef3e8f882c38d
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-delete-add-composite-main-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920014055-643440-update-legacy-unmanaged-cartesian-restart-cartesian-delete-add-composite-main-to-helper-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    command:
      - --port=80
    restart: unless-stopped
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-cartesian-restart-cartesian-delete-add-composite-main-to-helper
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-cartesian-restart-cartesian-delete-add-composite-main-to-helper/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged-cartesian restart cartesian-delete-add composite main-to-helper
    zh_CN: E2E legacy-unmanaged-cartesian restart cartesian-delete-add composite main-to-helper
  port_map: '19030'
  version: 1.0.0
  scheme: http
  index: /
