name: zimaos-e2e-legacy-unmanaged-ports-add-same-composite-main-to-main
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:4f90b33ddca9c4d4f06527070d6e503b16d71016edea036842be2a84e60c91cb
    container_name: zimaos-e2e-legacy-unmanaged-ports-add-same-composite-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921171621-1205145-update-legacy-unmanaged-ports-add-same-composite-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '18226'
        protocol: tcp
      - target: 10104
        published: '30210'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
  helper:
    image: alpine:3.20@sha256:c64c687cbea9300178b30c95835354e34c4e4febc4badfe27102879de0483b5e
    container_name: zimaos-e2e-legacy-unmanaged-ports-add-same-composite-main-to-main-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921171621-1205145-update-legacy-unmanaged-ports-add-same-composite-main-to-main-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    restart: unless-stopped
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-ports-add-same-composite-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-ports-add-same-composite-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged ports add-same composite main-to-main
    zh_CN: E2E legacy-unmanaged ports add-same composite main-to-main
  port_map: '18226'
  version: 1.1.0
  scheme: http
  index: /
