name: zimaos-e2e-legacy-unmanaged-volumes-local-unchanged-upstream-modify-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-unmanaged-volumes-local-unchanged-upstream-modify-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260921171621-1205145-update-legacy-unmanaged-volumes-local-unchanged-upstream-modify-single-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
      - type: bind
        source: /DATA/AppData/zimaos-e2e-legacy-unmanaged-volumes-local-unchanged-upstream-modify-single-main-to-main/case-base-a
        target: /e2e-case-a
    ports:
      - target: 80
        published: '18263'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-volumes-local-unchanged-upstream-modify-single-main-to-main
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-volumes-local-unchanged-upstream-modify-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged volumes local-unchanged-upstream-modify single main-to-main
    zh_CN: E2E legacy-unmanaged volumes local-unchanged-upstream-modify single main-to-main
  port_map: '18263'
  version: 1.0.0
  scheme: http
  index: /
