name: zimaos-e2e-image-single-versionless-m1006084817-p18111
services:
  web:
    image: traefik/whoami:latest@sha256:fb8458a97e9695115b0367e5ecf2a1a72de48b306acccccd01455b46334d2300
    container_name: zimaos-e2e-image-single-versionless-m1006084817-p18111-web
    restart: on-failure
    ports:
      - target: 80
        published: '18111'
        protocol: tcp
      - target: 8081
        published: '19105'
        protocol: tcp
    environment:
      ZIMAOS_E2E_BASELINE: 20261006085004-1865673-image-single-versionless
      E2E_SHARED: upstream-loses
      E2E_LOCAL_DELETE_UPSTREAM_MODIFY: upstream-value
      E2E_LOCAL_EMPTY_UPSTREAM_VALUE: upstream-value
      E2E_LOCAL_VALUE_UPSTREAM_EMPTY: ''
      E2E_BOTH_EMPTY: ''
      ZIMAOS_E2E_UPSTREAM_LATEST: must-not-apply
      E2E_UPSTREAM_ADDED: upstream-value
      E2E_BOTH_ADD_SAME: upstream-loses
      E2E_DIFFERENT_UPSTREAM: upstream-value
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
      - type: bind
        source: /DATA/AppData/$AppID/e2e-upstream-must-not-apply
        target: /e2e-upstream-must-not-apply
    command:
      - --port=80
      - --name=upstream-must-not-apply
x-casaos:
  id: org.zimaos.e2e.image-single-versionless.m1006084817.p18111
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.image-single-versionless.m1006084817.p18111/assets/icon.svg
  title:
    en_US: E2E Image Single Without Version
    zh_CN: E2E Image Single Without Version
  port_map: '18111'
  version: 1.0.0
  scheme: http
  index: /
