name: zimaos-e2e-legacy-previous-base-exact-history-volumes-cartesian-add-delete-single-main-to-main
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:9564f83910c98c3bea640803d8014b5c586b4bd556906d1afab21c7e7f1e4d4c
    container_name: zimaos-e2e-legacy-previous-base-exact-history-volumes-cartesian-add-delete-single-main-to-main-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260923205535-1808238-update-legacy-previous-base-exact-history-volumes-cartesian-add-delete-single-main-to-main
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19727'
        protocol: tcp
    restart: unless-stopped
    command:
      - --port=80
x-casaos:
  id: org.zimaos.e2e.legacy-previous-base-exact-history-volumes-cartesian-add-delete-single-main-to-main
  main: web
  icon: https://raw.githubusercontent.com/Dengwii/CasaOS-AppStore/refs/heads/gh-pages/apps/org.zimaos.e2e.legacy-previous-base-exact-history-volumes-cartesian-add-delete-single-main-to-main/assets/icon.svg
  title:
    en_US: E2E legacy-previous-base-exact-history volumes cartesian-add-delete single main-to-main
    zh_CN: E2E legacy-previous-base-exact-history volumes cartesian-add-delete single main-to-main
  port_map: '19727'
  version: 1.1.0
  scheme: http
  index: /
