name: zimaos-e2e-ports-local-unchanged-upstream-delete-composite
services:
  web:
    image: traefik/whoami:v1.10.3
    container_name: zimaos-e2e-ports-local-unchanged-upstream-delete-composite-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917140034-116715-update-ports-local-unchanged-upstream-delete-composite
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    ports:
      - target: 10028
        published: '30056'
        protocol: tcp
  helper:
    image: alpine:3.20
    container_name: zimaos-e2e-ports-local-unchanged-upstream-delete-composite-helper
    network_mode: bridge
    restart: unless-stopped
    environment:
      E2E_SECONDARY_BASELINE: 20260917140034-116715-update-ports-local-unchanged-upstream-delete-composite
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
x-casaos:
  id: org.zimaos.e2e.ports-local-unchanged-upstream-delete-composite
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.ports-local-unchanged-upstream-delete-composite/assets/icon.svg
  title:
    en_US: E2E Ports Local-Unchanged-Upstream-Delete Composite
    zh_CN: E2E Ports Local-Unchanged-Upstream-Delete Composite
  port_map: '18214'
  version: 1.0.0
