name: zimaos-e2e-restart-add-different-single
services:
  web:
    image: traefik/whoami:v1.11.0
    container_name: zimaos-e2e-restart-add-different-single-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260917214521-225176-update-restart-add-different-single
    ports:
      - target: 80
        published: '18203'
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    command:
      - --port=80
    restart: always
x-casaos:
  id: org.zimaos.e2e.restart-add-different-single
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.restart-add-different-single/assets/icon.svg
  title:
    en_US: E2E Restart Add-Different Single
    zh_CN: E2E Restart Add-Different Single
  port_map: '18203'
  version: 1.1.0
