name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-delete-modify-composite-main-to-helper
services:
  web:
    image: traefik/whoami:v1.11.0@sha256:c2c89736959e8830c3db090e2f54500499ceb0460267f91dce494728d7327770
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-delete-modify-composite-main-to-helper-web
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920162142-879240-update-legacy-unmanaged-cartesian-restart-cartesian-delete-modify-composite-main-to-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base
        target: /e2e-base
    ports:
      - target: 80
        published: '19034'
        protocol: tcp
    command:
      - --port=80
    restart: unless-stopped
  helper:
    image: traefik/whoami:v1.10.3@sha256:7865582efaa90720f146cbdb411756b5e85dafcb0f608396a48c4d2d0b1218ad
    container_name: zimaos-e2e-legacy-unmanaged-cartesian-restart-cartesian-delete-modify-composite-main-to-helper-helper
    network_mode: bridge
    environment:
      ZIMAOS_E2E_BASELINE: 20260920162142-879240-update-legacy-unmanaged-cartesian-restart-cartesian-delete-modify-composite-main-to-helper-helper
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/e2e-base-helper
        target: /e2e-base-helper
    command:
      - --port=80
    restart: on-failure
x-casaos:
  id: org.zimaos.e2e.legacy-unmanaged-cartesian-restart-cartesian-delete-modify-composite-main-to-helper
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.legacy-unmanaged-cartesian-restart-cartesian-delete-modify-composite-main-to-helper/assets/icon.svg
  title:
    en_US: E2E legacy-unmanaged-cartesian restart cartesian-delete-modify composite main-to-helper
    zh_CN: E2E legacy-unmanaged-cartesian restart cartesian-delete-modify composite main-to-helper
  port_map: '19034'
  version: 1.1.0
  scheme: http
  index: /
