name: zimaos-e2e-volumes-add-same-composite
services:
  web:
    image: traefik/whoami:v1.10.3@sha256:c899811bc4a1f63a1273c612e15f1bea6514a19c7b08143dbbdef3e8f882c38d
    container_name: zimaos-e2e-volumes-add-same-composite-web
    environment:
      ZIMAOS_E2E_BASELINE: 20260917103026-76552-update-volumes-add-same-composite
    restart: unless-stopped
    ports:
      - target: 80
        published: '18234'
        protocol: tcp
    command:
      - --port=80
    volumes: []
  helper:
    image: alpine:3.20@sha256:c64c687cbea9300178b30c95835354e34c4e4febc4badfe27102879de0483b5e
    container_name: zimaos-e2e-volumes-add-same-composite-helper
    restart: unless-stopped
    environment:
      E2E_SECONDARY_BASELINE: 20260917103026-76552-update-volumes-add-same-composite
    command:
      - sh
      - -c
      - while true; do sleep 3600; done
x-casaos:
  id: org.zimaos.e2e.volumes-add-same-composite
  main: web
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.zimaos.e2e.volumes-add-same-composite/assets/icon.svg
  title:
    en_US: E2E Volumes Add-Same Composite
    zh_CN: E2E Volumes Add-Same Composite
  port_map: '18234'
  version: 1.0.0
