name: lucky
services:
  lucky:
    deploy:
      resources:
        reservations:
          memory: 64M
    image: gdy666/lucky:3.0.0@sha256:671d7a5e80484bdf218afb7b38695e6681271473a3510f986054c03953f2442d
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/lucky
        target: /goodluck
    environment:
      TZ: $TZ
    network_mode: host
    privileged: false
x-casaos:
  id: org.icewhale.lucky
  main: lucky
  icon: https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore@gh-pages/apps/org.icewhale.lucky/assets/icon.svg
  index: /
  title:
    en_US: Lucky
  port_map: "16601"
  scheme: http
  version: "3.0.0"
